# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: maven
        
    - name: Build strict-mark
      run: mvn -B --no-transfer-progress --update-snapshots package install --file strict-mark && mkdir staging && cp target/*.jar staging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish strict-mark to GitHub Packages Apache Maven
      run: mvn -DskipTests deploy -s $GITHUB_WORKSPACE/settings.xml --file strict-mark
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
  publish-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Strict Mark Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: main
          java-version: 11
          target-folder: strict-markdown/javadoc
          project: maven
